name: Auto hugo
on:
  push:
    branches: [ main ]
jobs:
  hugo-build:
    runs-on: ubuntu-latest
    steps:      
      - name: Check out repository ğŸš€
        uses: actions/checkout@v3
      - name: Setup hugo ğŸ¥–
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Set gokarna Theme ğŸ
        run: git submodule add https://github.com/xsmallbear/gokarna.git themes/gokarna
      - name: hugo Build ğŸ¤©
        run: hugo
      - name: Push github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: page
          commit_message: ${{ github.event.head_commit.message }}

       
